/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : bigint,
  'status' : ApplicationStatus,
  'appliedAt' : bigint,
  'studentId' : Principal,
  'jobId' : bigint,
  'message' : string,
}
export type ApplicationStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface EmployerProfile {
  'locationLat' : number,
  'locationLng' : number,
  'createdAt' : bigint,
  'businessName' : string,
  'businessType' : string,
  'address' : string,
  'contactNumber' : string,
}
export interface Job {
  'id' : bigint,
  'locationLat' : number,
  'locationLng' : number,
  'title' : string,
  'postedAt' : bigint,
  'tags' : Array<string>,
  'description' : string,
  'isActive' : boolean,
  'employerId' : Principal,
  'address' : string,
  'payAmount' : bigint,
  'category' : JobCategory,
  'payType' : PayType,
}
export type JobCategory = string;
export interface JobWithDistance { 'job' : Job, 'distanceKm' : number }
export type PayType = string;
export type Profile = { 'employer' : EmployerProfile } |
  { 'student' : StudentProfile };
export interface StudentProfile {
  'bio' : string,
  'locationLat' : number,
  'locationLng' : number,
  'name' : string,
  'createdAt' : bigint,
  'availability' : string,
  'skills' : Array<string>,
  'college' : string,
}
export interface UserProfile { 'name' : string, 'profileType' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyToJob' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEmployerProfile' : ActorMethod<[EmployerProfile], undefined>,
  'createStudentProfile' : ActorMethod<[StudentProfile], undefined>,
  'deleteJob' : ActorMethod<[bigint], undefined>,
  'getApplicationsForJob' : ActorMethod<[bigint], Array<Application>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJobById' : ActorMethod<[bigint], [] | [Job]>,
  'getJobsNearLocation' : ActorMethod<
    [number, number, number],
    Array<JobWithDistance>
  >,
  'getMyApplications' : ActorMethod<[], Array<Application>>,
  'getMyProfile' : ActorMethod<[], [] | [Profile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initSeedData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllActiveJobs' : ActorMethod<[], Array<Job>>,
  'listJobsByEmployer' : ActorMethod<[Principal], Array<Job>>,
  'postJob' : ActorMethod<[Job], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateApplicationStatus' : ActorMethod<
    [bigint, ApplicationStatus],
    undefined
  >,
  'updateEmployerProfile' : ActorMethod<[EmployerProfile], undefined>,
  'updateStudentProfile' : ActorMethod<[StudentProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];