/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EmployerProfile = IDL.Record({
  'locationLat' : IDL.Float64,
  'locationLng' : IDL.Float64,
  'createdAt' : IDL.Int,
  'businessName' : IDL.Text,
  'businessType' : IDL.Text,
  'address' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const StudentProfile = IDL.Record({
  'bio' : IDL.Text,
  'locationLat' : IDL.Float64,
  'locationLng' : IDL.Float64,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'availability' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
  'college' : IDL.Text,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Application = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'appliedAt' : IDL.Int,
  'studentId' : IDL.Principal,
  'jobId' : IDL.Nat,
  'message' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'profileType' : IDL.Text,
});
export const JobCategory = IDL.Text;
export const PayType = IDL.Text;
export const Job = IDL.Record({
  'id' : IDL.Nat,
  'locationLat' : IDL.Float64,
  'locationLng' : IDL.Float64,
  'title' : IDL.Text,
  'postedAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'employerId' : IDL.Principal,
  'address' : IDL.Text,
  'payAmount' : IDL.Nat,
  'category' : JobCategory,
  'payType' : PayType,
});
export const JobWithDistance = IDL.Record({
  'job' : Job,
  'distanceKm' : IDL.Float64,
});
export const Profile = IDL.Variant({
  'employer' : EmployerProfile,
  'student' : StudentProfile,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyToJob' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEmployerProfile' : IDL.Func([EmployerProfile], [], []),
  'createStudentProfile' : IDL.Func([StudentProfile], [], []),
  'deleteJob' : IDL.Func([IDL.Nat], [], []),
  'getApplicationsForJob' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Application)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJobById' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
  'getJobsNearLocation' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Vec(JobWithDistance)],
      ['query'],
    ),
  'getMyApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initSeedData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllActiveJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'listJobsByEmployer' : IDL.Func([IDL.Principal], [IDL.Vec(Job)], ['query']),
  'postJob' : IDL.Func([Job], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
  'updateEmployerProfile' : IDL.Func([EmployerProfile], [], []),
  'updateStudentProfile' : IDL.Func([StudentProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EmployerProfile = IDL.Record({
    'locationLat' : IDL.Float64,
    'locationLng' : IDL.Float64,
    'createdAt' : IDL.Int,
    'businessName' : IDL.Text,
    'businessType' : IDL.Text,
    'address' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const StudentProfile = IDL.Record({
    'bio' : IDL.Text,
    'locationLat' : IDL.Float64,
    'locationLng' : IDL.Float64,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'availability' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
    'college' : IDL.Text,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Application = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'appliedAt' : IDL.Int,
    'studentId' : IDL.Principal,
    'jobId' : IDL.Nat,
    'message' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'profileType' : IDL.Text,
  });
  const JobCategory = IDL.Text;
  const PayType = IDL.Text;
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'locationLat' : IDL.Float64,
    'locationLng' : IDL.Float64,
    'title' : IDL.Text,
    'postedAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'employerId' : IDL.Principal,
    'address' : IDL.Text,
    'payAmount' : IDL.Nat,
    'category' : JobCategory,
    'payType' : PayType,
  });
  const JobWithDistance = IDL.Record({
    'job' : Job,
    'distanceKm' : IDL.Float64,
  });
  const Profile = IDL.Variant({
    'employer' : EmployerProfile,
    'student' : StudentProfile,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyToJob' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEmployerProfile' : IDL.Func([EmployerProfile], [], []),
    'createStudentProfile' : IDL.Func([StudentProfile], [], []),
    'deleteJob' : IDL.Func([IDL.Nat], [], []),
    'getApplicationsForJob' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Application)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJobById' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
    'getJobsNearLocation' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Vec(JobWithDistance)],
        ['query'],
      ),
    'getMyApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initSeedData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllActiveJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'listJobsByEmployer' : IDL.Func([IDL.Principal], [IDL.Vec(Job)], ['query']),
    'postJob' : IDL.Func([Job], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
    'updateEmployerProfile' : IDL.Func([EmployerProfile], [], []),
    'updateStudentProfile' : IDL.Func([StudentProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };