/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface EmployerProfile {
    locationLat: number;
    locationLng: number;
    createdAt: bigint;
    businessName: string;
    businessType: string;
    address: string;
    contactNumber: string;
}
export interface StudentProfile {
    bio: string;
    locationLat: number;
    locationLng: number;
    name: string;
    createdAt: bigint;
    availability: string;
    skills: Array<string>;
    college: string;
}
export interface Job {
    id: bigint;
    locationLat: number;
    locationLng: number;
    title: string;
    postedAt: bigint;
    tags: Array<string>;
    description: string;
    isActive: boolean;
    employerId: Principal;
    address: string;
    payAmount: bigint;
    category: JobCategory;
    payType: PayType;
}
export interface Application {
    id: bigint;
    status: ApplicationStatus;
    appliedAt: bigint;
    studentId: Principal;
    jobId: bigint;
    message: string;
}
export type JobCategory = string;
export type Profile = {
    __kind__: "employer";
    employer: EmployerProfile;
} | {
    __kind__: "student";
    student: StudentProfile;
};
export type PayType = string;
export interface UserProfile {
    name: string;
    profileType: string;
}
export interface JobWithDistance {
    job: Job;
    distanceKm: number;
}
export enum ApplicationStatus {
    pending = "pending",
    rejected = "rejected",
    accepted = "accepted"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    applyToJob(jobId: bigint, message: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createEmployerProfile(profile: EmployerProfile): Promise<void>;
    createStudentProfile(profile: StudentProfile): Promise<void>;
    deleteJob(jobId: bigint): Promise<void>;
    getApplicationsForJob(jobId: bigint): Promise<Array<Application>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getJobById(id: bigint): Promise<Job | null>;
    getJobsNearLocation(lat: number, lng: number, radiusKm: number): Promise<Array<JobWithDistance>>;
    getMyApplications(): Promise<Array<Application>>;
    getMyProfile(): Promise<Profile | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initSeedData(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listAllActiveJobs(): Promise<Array<Job>>;
    listJobsByEmployer(employerId: Principal): Promise<Array<Job>>;
    postJob(job: Job): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateApplicationStatus(appId: bigint, status: ApplicationStatus): Promise<void>;
    updateEmployerProfile(profile: EmployerProfile): Promise<void>;
    updateStudentProfile(profile: StudentProfile): Promise<void>;
}
import type { Application as _Application, ApplicationStatus as _ApplicationStatus, EmployerProfile as _EmployerProfile, Job as _Job, Profile as _Profile, StudentProfile as _StudentProfile, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async applyToJob(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyToJob(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyToJob(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createEmployerProfile(arg0: EmployerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmployerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmployerProfile(arg0);
            return result;
        }
    }
    async createStudentProfile(arg0: StudentProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudentProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudentProfile(arg0);
            return result;
        }
    }
    async deleteJob(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return result;
        }
    }
    async getApplicationsForJob(arg0: bigint): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicationsForJob(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicationsForJob(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobById(arg0: bigint): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobById(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobById(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobsNearLocation(arg0: number, arg1: number, arg2: number): Promise<Array<JobWithDistance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsNearLocation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsNearLocation(arg0, arg1, arg2);
            return result;
        }
    }
    async getMyApplications(): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyApplications();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyApplications();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async initSeedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initSeedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSeedData();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllActiveJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllActiveJobs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllActiveJobs();
            return result;
        }
    }
    async listJobsByEmployer(arg0: Principal): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.listJobsByEmployer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listJobsByEmployer(arg0);
            return result;
        }
    }
    async postJob(arg0: Job): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.postJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postJob(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateApplicationStatus(arg0: bigint, arg1: ApplicationStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplicationStatus(arg0, to_candid_ApplicationStatus_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplicationStatus(arg0, to_candid_ApplicationStatus_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateEmployerProfile(arg0: EmployerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployerProfile(arg0);
            return result;
        }
    }
    async updateStudentProfile(arg0: StudentProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudentProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudentProfile(arg0);
            return result;
        }
    }
}
function from_candid_ApplicationStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Application_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Application): Application {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Job]): Job | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : from_candid_Profile_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ApplicationStatus;
    appliedAt: bigint;
    studentId: Principal;
    jobId: bigint;
    message: string;
}): {
    id: bigint;
    status: ApplicationStatus;
    appliedAt: bigint;
    studentId: Principal;
    jobId: bigint;
    message: string;
} {
    return {
        id: value.id,
        status: from_candid_ApplicationStatus_n6(_uploadFile, _downloadFile, value.status),
        appliedAt: value.appliedAt,
        studentId: value.studentId,
        jobId: value.jobId,
        message: value.message
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    employer: _EmployerProfile;
} | {
    student: _StudentProfile;
}): {
    __kind__: "employer";
    employer: EmployerProfile;
} | {
    __kind__: "student";
    student: StudentProfile;
} {
    return "employer" in value ? {
        __kind__: "employer",
        employer: value.employer
    } : "student" in value ? {
        __kind__: "student",
        student: value.student
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): ApplicationStatus {
    return "pending" in value ? ApplicationStatus.pending : "rejected" in value ? ApplicationStatus.rejected : "accepted" in value ? ApplicationStatus.accepted : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Application>): Array<Application> {
    return value.map((x)=>from_candid_Application_n4(_uploadFile, _downloadFile, x));
}
function to_candid_ApplicationStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): _ApplicationStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
} {
    return value == ApplicationStatus.pending ? {
        pending: null
    } : value == ApplicationStatus.rejected ? {
        rejected: null
    } : value == ApplicationStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
